DROP TABLE IF EXISTS line_stop;
DROP TABLE IF EXISTS line_segment;
DROP TABLE IF EXISTS line;
DROP TABLE IF EXISTS stop;

CREATE TABLE stop(
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE line(
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    first_stop INTEGER NOT NULL REFERENCES stop ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE line_stop(
    line_id INTEGER NOT NULL REFERENCES line ON DELETE CASCADE ON UPDATE CASCADE,
    stop_id INTEGER NOT NULL REFERENCES stop ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE line_segment(
    id SERIAL PRIMARY KEY,
    line INTEGER NOT NULL REFERENCES line  ON DELETE CASCADE ON UPDATE CASCADE,
    ls_index INTEGER NOT NULL,
    next_stop INTEGER NOT NULL REFERENCES stop ON DELETE CASCADE ON UPDATE CASCADE,
    time_diff INTEGER CHECK (time_diff > 0),
    capacity INTEGER CHECK (capacity > 0),
    passengers INTEGER CHECK (passengers >= 0),
    UNIQUE(line, ls_index)
);